import { StyleSheet, Dimensions, StatusBar } from "react-native";
import Colors from "../../../constants/Colors";

export default StyleSheet.create({
	page: {
		flex: 1,
		width: Dimensions.get("window").width,
		backgroundColor: Colors.light.primary,
	},
	subHead: {
		paddingHorizontal: 15,
		height: 45,
		backgroundColor: Colors.accentDark,
		alignItems: "center",
		justifyContent: "space-between",
		flexDirection: "row",
	},
	subHeadDayInfo: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	subHeadDay: {
		textTransform: "capitalize",
		color: Colors.white,
		fontSize: 16,
		fontFamily: "Rubik-Bold",
	},
	subHeadDayBounds: {
		color: Colors.white80,
		fontSize: 12,
		fontFamily: "Rubik-Regular",
	},
	subHeadButton: {
		borderRadius: 18,
		height: 36,
		width: 36,
		alignItems: "center",
		justifyContent: "center",
	},
	classes: {
		paddingHorizontal: 15,
		paddingBottom: 20,
		gap: 20,
	},
	class: {
		backgroundColor: Colors.light.secondary,
		borderRadius: 6,
	},
	classHeader: {
		padding: 10,
		flexDirection: "row",
		gap: 12,
		alignItems: "center",
		borderRadius: 6,
	},
	average: {
		fontSize: 12,
		fontFamily: "Rubik-Regular",
		color: Colors.black,
		width: 45,
		paddingVertical: 5,
		textAlign: "center",
		backgroundColor: Colors.white,
		borderRadius: 5,
		alignItems: "center",
		justifyContent: "center",
	},
	notes: {
		paddingVertical: 15,
		paddingHorizontal: 20,
		flexWrap: "wrap",
		flexDirection: "row",
		gap: 25,
	},
	note: {
		flexDirection: "row",
		gap: 5,
		padding: 2,
		borderBottomColor: Colors.lightBlue,
	},
	noteContent: {
		color: Colors.light.header80,
	},
	coef: {
		color: Colors.light.gray,
		fontSize: 10,
	},
	resourceTitle: {
		fontSize: 14,
		color: Colors.white,
		flex: 1,
		fontFamily: "Rubik-Regular",
		lineHeight: 21,
	},
	resourceContainer: {
		gap: 10,
	},
	meanText: {
		fontSize: 12,
		color: Colors.light.header80,
		fontFamily: "Rubik-Italic",
	},
	noteHeader: {
		paddingVertical: 15,
		paddingHorizontal: 20,
	},
	noteHeaderLabel: {
		fontSize: 20,
		color: Colors.light.header,
		fontFamily: "Rubik-Bold",
	},
	meanContainer: {
		paddingBottom: 15,
		paddingHorizontal: 20,
		gap: 10,
	},
	userMeanContent: {
		flexDirection: "row",
		backgroundColor: Colors.light.secondary,
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderRadius: 6,
		alignItems: "center",
	},
	userMeanLabel: {
		fontSize: 14,
		color: Colors.light.header80,
		fontFamily: "Rubik-Regular",
		flex: 1,
	},
	userMeanValue: {
		color: Colors.light.header,
		fontFamily: "Rubik-Bold",
		fontSize: 14,
	},
	classMeanContent: {
		flex: 1,
		alignItems: "center",
		backgroundColor: Colors.light.secondary,
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderRadius: 6,
	},
	notesRow: {
		flexDirection: "row",
		gap: 10,
	},
	connectionPage: {
		flex: 1,
	},
	connectionHead: {
		padding: 15,
	},
	connectButton: {
		paddingVertical: 14,
		marginTop: "auto",
		backgroundColor: Colors.accent,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: 10,
		gap: 10,
	},
	connectButtonText: {
		fontFamily: "Rubik-Bold",
		color: Colors.white,
	},
	errorText: {
		color: Colors.red,
		fontSize: 12,
		marginLeft: 5,
	},
	fieldTitle: {
		fontFamily: "Rubik-Regular",
		color: Colors.light.header80,
		fontSize: 15,
		marginTop: 2,
	},
	fieldTitleContainer: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 4,
		marginLeft: 8,
		gap: 5,
	},
	fieldContainer: {
		borderWidth: 1,
		borderColor: Colors.light.borderColor,
		borderRadius: 10,
		marginBottom: 5,
		flexDirection: "row",
		gap: 5,
	},
	fieldInput: {
		flex: 1,
		fontFamily: "Rubik-Regular",
		paddingHorizontal: 15,
		paddingVertical: 10,
		color: Colors.light.header,
	},
	passwordVisibility: {
		alignItems: "center",
		justifyContent: "center",
		marginRight: 15,
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	form: {
		flex: 1,
		padding: 15,
		gap: 15,
	},
	averageValue: {
		fontFamily: "Rubik-Regular",
		fontSize: 12,
		color: Colors.black,
	},
	averageSubValue: {
		fontFamily: "Rubik-Regular",
		fontSize: 10,
		color: Colors.black80,
	},
	headText: {
		flex: 1,
	},
	resourceResult: {
		fontFamily: "Rubik-Regular",
		fontSize: 10,
		color: Colors.white80,
	},
	pageModalTitle: {
		fontFamily: "Rubik-Bold",
		fontSize: 16,
		color: Colors.light.header,
	},
	pageModalSubtitle: {
		fontFamily: "Rubik-Regular",
		fontSize: 12,
		color: Colors.light.gray,
		textTransform: "capitalize",
	},
	resourceScroll: {
		marginBottom: StatusBar.currentHeight,
	},
	ueButton: {
		backgroundColor: Colors.green,
		borderRadius: 6,
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 15,
		gap: 10,
	},
	ueButtonText: {
		color: Colors.white,
		fontSize: 14,
		fontFamily: "Rubik-Regular",
		marginRight: "auto",
	},
});
